package tr.com.havelsan.limanpgtool.gateway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserroleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserroleAllPropertiesEquals(Userrole expected, Userrole actual) {
        assertUserroleAutoGeneratedPropertiesEquals(expected, actual);
        assertUserroleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserroleAllUpdatablePropertiesEquals(Userrole expected, Userrole actual) {
        assertUserroleUpdatableFieldsEquals(expected, actual);
        assertUserroleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserroleAutoGeneratedPropertiesEquals(Userrole expected, Userrole actual) {
        assertThat(actual)
            .as("Verify Userrole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserroleUpdatableFieldsEquals(Userrole expected, Userrole actual) {
        assertThat(actual)
            .as("Verify Userrole relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserroleUpdatableRelationshipsEquals(Userrole expected, Userrole actual) {
        // empty method
    }
}
